### ISSUE TITLE
Fronto and Marcus Aurelius - Week 1

### ISSUE THREAD

**Issue by egunner1** [ChiaraPalladino/furesearch#24]
Okay @egunner1, I have good news and bad news. 
1) The good news is that I was able to download a TXT version of Fronto's volume from Archive.org. It is here: https://github.com/ChiaraPalladino/furesearch/blob/main/sentiment-analysis/fronto/fronto-postHOCR 
2) The bad news is that, since this was done a while ago, the character recognition is far from perfect. You will see that many corrections are necessary for the Latin to make sense. 

Your task for the rest of this week is to: 
* Copy the text of the relevant letters in another txt file 
* Correct it by looking at the original edition. Search some latin keywords from the edition to find the location of each letter in the file. 

Once you are done, upload the txt file on GitHub and I will process it to start the annotation process.  
The only workaround to this, unfortunately, is to run a new OCR from my machine, but I need a completely new scanned copy of the edition, which I can't get at the moment. 

------------

I finished correcting the text and uploaded the file to the Fronto folder. One sentence in Ad M. Caes II.2 is a quotation in Greek---is it possible to skip that sentence and still analyze the rest of the letter, or should I select a different one?

**Comment by ChiaraPalladino** [comment]
the text should be available in the spreadsheet Lizzy! 

Also, as discussed in our meeting: discard anything that is not Latin from the spreadsheet.
