### ISSUE TITLE
Odyssey Lines 9.378-397

### ISSUE THREAD

**Issue by mariacurley** [ChiaraPalladino/furesearch#30]
@ChiaraPalladino The section we discussed over our meeting included lines 378-397, especially the segments about the shipwright and the smith. I am having trouble making sense of it in both Chapman's and Pope's translations.

Also, when I initially tried to create this issue, I mistakenly deleted the line of the Project Roadmap that was Aligning the Odyssey - Week 2. I meant to report that I had completed the work for week 2 (Pope's translation) and would be skipping ahead to one of the more modern ones, most likely Lombardo.

6/17 edit: I have started to look at Lombardo's translation, and I noticed that his line numbers are different. For the previous translations, I have been starting on the line that talks about feeding Polyphemus the wine three times, which was line 361 on both. In Lombardo's translation, this is line 358. I am not sure how to handle this. Should I pick a separate translation? This is the same issue in Fitzgerald's translation.

**Comment by ChiaraPalladino** [comment]
Very quickly before I take the other things - Lombardo's translation will need to be realigned manually, without looking at the line numbers. If you feel like it's too hard or time-consuming, of course feel free to pick Fitzgerald's or Emily Wilson's.

**Comment by ChiaraPalladino** [comment]
@mariacurley I have started reviewing this passage from the _Odyssey_ . The translations are definitely atrocious so there is a lot of work to be done. 

To make things easier, I have re-made the alignment of Chapman. I still need to work on the most complicated parts, but it could be useful for you to have a look at it: https://ugarit.ialigner.com/text.php?id=42815 
We'll discuss the text in our next meeting.
