### ISSUE TITLE
Aligning the Odyssey - Week 4

### ISSUE THREAD

**Issue by ChiaraPalladino** [ChiaraPalladino/furesearch#39]
From @mariacurley report: 

Week 4 Report: I finished Butler's translation, which was written in prose. One section I was a little confused about in lines 522-542 had a phrase [in brackets like this.] I didn't know why it was written that way, but I included all the text, including what's in brackets, in my alignment. Next week I will be starting with Fitzgerald's translation from 1974.

**Comment by ChiaraPalladino** [comment]
@mariacurley could you please add links to the problematic alignments? To send public links, go to your dashboard, check the "last modified" and click on "preview" 



![Image](https://github.com/ChiaraPalladino/furesearch/assets/15249889/f203aa7c-5cb4-4c21-84de-7a2acfc8507c)


Then you can use the URL for the alignment you want. 

This will simplify checks, since you now have a lot of alignments!

**Comment by mariacurley** [comment]
Here is the link to the Butler translation I was wondering about: [https://ugarit.ialigner.com/text.php?id=42813](url)

**Comment by ChiaraPalladino** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Open Issues](https://trello.com/c/WvgXDw4A/4-open-issues)
