### ISSUE TITLE
Anabasis - Back end of Book 3 (3.4.23-3.5.13) being uncooperative with reality [update]

### ISSUE THREAD

**Issue by CianColgan** [ChiaraPalladino/furesearch#41]
#37 
# Update on our meeting (7/1) discussion
For reference, this is the area of interest:
![Capture8](https://github.com/ChiaraPalladino/furesearch/assets/170037960/b0efdb06-d7ca-4b16-b103-ab01f24f4a8c)

## The Problem
The current route mapped up to 3.4.24 looks like this:
![Capture](https://github.com/ChiaraPalladino/furesearch/assets/170037960/72e17fd7-ef8d-4af1-8541-aea03f8d41a9)

However, by the end of Book 3 they have to travel a cumulative distance of ~105km (~78.5km away [3.4.32-3.4.37]), then retracing steps for ~27km [3.5.13]). However, at their max displacement this would put them by the Centrities river, deep in the Carduchian Mountains, an area they don't reach until Book 4 [4.3.1])This is how it would look with my measurements plotted as is:
![Capture1edit](https://github.com/ChiaraPalladino/furesearch/assets/170037960/504f4c26-3b6d-4d04-b8ba-32ef65289351)

I'm already making some allowances for terrain/pathing, otherwise the distance would be even more exacerbated. Here's what it would look like if I stuck to the reasonable maximum of the literal measurements:
![Capture8edit](https://github.com/ChiaraPalladino/furesearch/assets/170037960/39bcef4f-8d06-409e-aa6c-be053d590c26)

There are no known locations he visited in this section, just barbarian villages. The closest we get is that "they caught sight of a palace of some sort, with many villages round about it, and they observed that the road to this place passed over high hills, which stretched down from the mountain at whose foot the villages were situated," (Anabasis 3.4.24). However, while it would be immensely helpful, I cannot find any identifiable locations for this palace or these high hills.

### 1. Shifts (My current choice)
In the interest of a continuous journey line, I was planning on shifting the two most recently plotted points back and finishing out the route. The trade-off is that this violates the 4 stage measurement given in 3.4.23 (and most future measurements, though not to such an extreme degree) for a more accurate rendering of where Xenophon says he is and what geography he describes. So, the end of Book 3 would look something like this (including additional Polygon radii which are not plotted as of this screenshot):
![Capture3edit2](https://github.com/ChiaraPalladino/furesearch/assets/170037960/261ba7d1-06ea-4adb-a6b0-2ec3b80a6eb7)
![Capture3edit](https://github.com/ChiaraPalladino/furesearch/assets/170037960/cd81da10-1c3d-4c7e-a3ae-a6c69deebec0)

### 2. No shifts until necessary
Another option is to keep the journey as I have it plotted now (up to 3.4.24; mostly accurate when accounting for terrain/meandering path), but violate future measurements of Book 3. The trade-off is that this keeps the route as consistent with the text as possible for as long as possible, but then abruptly all of the cumulative errors hit at once and it's suddenly deeply violates all measurements from 3.4.24-3.5.13:
![Capture9edit](https://github.com/ChiaraPalladino/furesearch/assets/170037960/4e419046-d71d-4388-8b7c-ef033705ee09)
I don't want to do this because it doesn't seem consistent or reasonable for me to stick to Xenophon's measurements as much as possible only to severely distort them in the name of geography. It feels like any benefit I'd get from preserving them up to 3.4.23 is negated by immediately violating them from 3.4.24-3.5.13.

### 3. No continuous journey
Another option is to split up the journey line from Book 3 to Book 4. So Book 3 would be consistent with the measurements Xenophon gives (but not the geography) and end basically in Armenia. then Book 4 would start where it's logical for it to start (at the foot of the Carduchian Mountains) and proceed as normal:
![Capture8edit2](https://github.com/ChiaraPalladino/furesearch/assets/170037960/c8db5c90-e135-4117-b222-e3b601d3e448)

This feels like a reasonable option if I was interested in sticking as close to the journey measurements as Xenophon gives. However, I think the underlying goal for this project is to map with respects to the narrative. Therefore, geography would be more important than measurements beacuse it does a better job of reflecting the narrative of Xenophon's _Anabasis_.

### 4. A bonus hairbrained scheme
_I'm going to preface this by saying I don't think this option should be what I go with right away because it involves me estimating at what Xenophon might have actually done based on his measurements and the geography, even though he doesn't explicitly say he did this, and we talked about that not being in the scope of this research period._

However, if we assume that Xenophon gave reasonably accurate measurements, and the modern day value of the measurements are well-estimated, then I suspect he may have actually taken a path like this:
![Capture7edit](https://github.com/ChiaraPalladino/furesearch/assets/170037960/58bf94dc-5b0b-4b2a-84b5-2287b3507b80)
**My reasoning:**
* There's a river (The Little Kahbur, a tributary of the Tigris) that Xenophon straight up does not explicitly mention crossing or even encountering. However, he would've had to cross it in order to follow the eastern bank of the Tigris
* This region is mountain foothills and plains, similar geography Xenophon mentions he traveled through. Furthermore, it's likely that there are a plethora of villages in this region that the Ten Thousand could have visited, looted, skirmished with Tissaphernes over, watched Tissaphernes burn, and burned themselves (3.4.24-3.5.13/end of Book 3)
* If they circled around in this region, this would explain why he traveled for so long (and also give more space for the apparently notable number of villages to exist in), while still being consistent with the geography, their stopping point, and Xenophon's overall narrative

**Problems:**
* There is no explicit textual evidence mentioning they took this detour
    * Just because Xenophon never explicitly mentions they crossed the Little Khabur does not mean he didn't; it's a jump to assume he circled around.
    * If they circled around the river (either because they thought it was the Tigris or because they needed to cross), it feels like they would know that they're doing that because they would literally be able to see where they just were on the opposite shore, and therefore it would seem to me to be noteworthy enough to include in the narrative.
    * Furthermore, it may be implied when he says, when talking about the logisticss of marching troops, "For if the wings draw together, either because a road is unusually narrow or because mountains or a bridge make it necessary, it is inevitable that the hoplites should be squeezed out of line and should march with difficulty..." (3.4.19)
        * This is before their 4 stage march (3.4.23), but it implies that they were expecting to cross more mountain passes and bridges during those 4 stages, so the ease that this formation provided could be why Xenophon doesn't mention them in the text
    * While the CAWM map tiles shows the Little Khabur stopping after a certain point, the ArcGIS basemap shows that it does continue, so they would still need to cross
        * However, to counter-counterclaim this point, the Ten Thousand are marching through winter, when the waters are lowest, so if they're circling the headwaters of the Little Khabur it could be mostly dried up and they wouldn't see it as crossing a river

**Comment by ChiaraPalladino** [comment]
Mmmm...yeah, **Option 1** is definitely the only reasonable one here, with the most accurate documentation possible, of course. I have some favor for Option 4 because it would give the impression of an inconsistent narrative - but then again, Xenophon **does not** interrupt his path here. So we would still be introducing evidence that is not actually in the text. 

I am a little less concerned in this case because it sounds like the core problem is the measurement given by Xenophon, and there is all sorts of arguments that could be made to justify the discrepancy. Measurements in antiquity are way less accurate than ours, so it is very understandable that they may not map perfectly onto a mathematical calculation. Furthermore, as we know all too well, Xenophon is extremely unreliable when it comes to these things. 

I still do not have access to the print version of the _Barrington Atlas_ to check the problem of Mespilae, I'll let you know as soon as I have some info. I'll talk with my Assyriology colleague in Israel when he comes back from vacation, to see if he can point me in a better direction.
