### ISSUE TITLE
Aristophanes - Week 7 - Prayers and wishes

### ISSUE THREAD

**Issue by ChiaraPalladino** [ChiaraPalladino/furesearch#44]
Adding a task here so that we keep track of things: 

* Add formatting and specific references to lines and passages in the decisions document on Wasps. See issue https://github.com/ChiaraPalladino/furesearch/issues/38 

End of week update:
I am in the middle of going through my previous documentation and adding the verse numbers on them. Once that is complete, the documents will be updated.
This week I did _Clouds_ sentence numbers 31-95, ending on verse 924. A lot of the sentences I have worked on earlier this week seemed to be neutral, which makes me a bit suspicious that maybe I am doing something wrong, but as of right now I stand by it. Other than that, no issues to report.

**Comment by ChiaraPalladino** [comment]
@bailsy6 I am largely in agreement with you on most choices in _Clouds_. I have changed a couple that were, in my opinion, more clearly positive or negative. 

I wonder, however, if we should have some specific guidelines for prayers. These are sometimes very similar to exhortations to violence, in the sense that the content of the prayer may be positive or negative, but it may also be different from its general sentiment (the suppliant may be fearful, aggressive, or happy). Sometimes a prayer may simply be an exhortation, although I don't know if the address to the gods should be positive by default. 
I am mostly thinking about sentences 61-63 here.

**Comment by bailsy6** [comment]
Okay, here is an idea of guidelines for prayers. Let me know if you think this covers all bases.

A prayer can have different sentiments that depend on content. 
-If the speaker is speaking positively to a god, they would most likely be making an appeal or expressing gratitude. “Making an appeal” can be done by expressing reverence or making promises towards the gods.
-If the prayer has a negative sentiment, it could contain a complaint, a curse, a fear, etc. 
-An expression of fear _of_ the gods could also be a positive sentiment, if it is done with the purpose of flattery.

**Comment by ChiaraPalladino** [comment]
> -If the speaker is speaking positively to a god, they would most likely be making an appeal or expressing gratitude. “Making an appeal” can be done by expressing reverence or making promises towards the gods. 

So this would be mostly positive sentiment, correct?

> -If the prayer has a negative sentiment, it could contain a complaint, a curse, a fear, etc. 

This would of course be negative. This would include many of those prayers where the suppliant hopes something bad will happen to another character, which are quite common in Aristophanes. 

> -An expression of fear _of_ the gods could also be a positive sentiment, if it is done with the purpose of flattery.

That's very true. Probably worth documenting as part of the general guidelines. 

I am not sure if this covers all the bases but it's definitely a good start. Something to talk about in our meeting tomorrow.

**Comment by ChiaraPalladino** [comment]
Here is another typology that was difficult to me: 

* When the prayer is for a god to remove an obstacle / prevent a threat or menace / keep something bad away or avoid it from happening. 

Honestly, I do not know how this should be classified. It could go either way, maybe even "mixed" sentiment.

**Comment by ChiaraPalladino** [comment]
Current guidelines detailed here: https://github.com/ChiaraPalladino/furesearch/tree/main/sentiment-analysis#particulars-prayers-and-supplications
