### ISSUE TITLE
Ugarit Not Working

### ISSUE THREAD

**Issue by mariacurley** [ChiaraPalladino/furesearch#45]
When I open Ugarit, I get an alert that says "Account Suspended", no matter what browser I open it from (including on my phone). It was working fine yesterday. It says "contact your hosting provider for more information", so I am writing to the email it provided now.

**Comment by ChiaraPalladino** [comment]
Hi Maria, it is probably some issue with the server. In my experience, it gets resolved in a couple of days. If it persists tomorrow, I'll contact the developer.

**Comment by mariacurley** [comment]
I have checked a few times since arriving at the beach, and it was down this morning but is up now!

**Comment by ChiaraPalladino** [comment]
yeah, I wrote an email to the developer - turns out they'd forgotten to renew the server subscription :)

**Comment by ChiaraPalladino** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Open Issues](https://trello.com/c/WvgXDw4A/4-open-issues)

**Comment by ChiaraPalladino** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Sample issue](https://trello.com/c/tASzxCrM/5-sample-issue)
