### ISSUE TITLE
Pharsalia - Week 8

### ISSUE THREAD

**Issue by ChiaraPalladino** [ChiaraPalladino/furesearch#49]
Adding a task discussed in the meeting just to keep track of things: 

* Make sure to update the documentation with the explanation of the violence score and with the color code in the spreadsheet

**Comment by ChiaraPalladino** [comment]
@aspainhour1 question: does the yellow on the spreadsheet indicate areas where you are **only** uncertain about the alignment with the translation? if so, I have corrected all of them and the color can be reset. Let me know if you also needed to revise the sentiment score, I haven't re-looked at it.

**Comment by aspainhour1** [comment]
I am almost done with the spreadsheet. I had a death in my family yesterday and it derailed my progress. I plan to be done with it by Monday of next week. If you have time could you look at the sentiment I have assigned to the following sentences: 145, 149, 160, 165, 173, and 183? I have left comments detailing the issues with each one of them.

**Comment by ChiaraPalladino** [comment]
I'm so sorry Alexis, take all the time you need. I'll look into these asap.

**Comment by aspainhour1** [comment]
Thank you. I have uploaded the spreadsheet!
