### ISSUE TITLE
Aristophanes - Week 1

### ISSUE THREAD

**Issue by ChiaraPalladino** [ChiaraPalladino/furesearch#8]
Read _Wasps_ in order to fully grasp the context. Analyzed the first 15 sentences in the spreadsheet, but will need to circle back to a couple of them as I am having trouble with them. I have been doing online searching for various references Aristophanes makes to ensure I understand the jokes to the best of my ability. Created a possible set of criteria for the "fun" score to guide my analysis. Working criteria is as follows:
**How much does the line rely on a joke or punchline to get the point across?
2: Very fun. The line is mostly for entertainment or a laugh. Possibly relies on the audience’s understanding of a certain politician, event, etc. to make sense.
1: Fun. The line has unnecessary aspects intended only for laughs, but still is mostly plot relevance.
0: Neutral. The line is straightforward and is intended to advance the plot.
-1: Serious. The line lacks humor and has little nonessential quips.
-2: Very serious. Has no “fluff,” possibly grim topic delivered with no humor.
I will be asking for some guidance on this criteria to make sure it is reasonable/useful.

**Comment by ChiaraPalladino** [comment]
@bailsy6  I think these criteria make enough sense to start. I am looking at your early results and have corrected some things, so don't be surprised if a couple of values have changed. 

For now, three things: 
- Add the initial criteria you established to the Documentation file so that we don't lose them: https://github.com/ChiaraPalladino/furesearch/blob/main/sentiment-analysis/aristophanes/aristophanes-documentation.md. 
- In the spreadsheet, I have split the column of "Relevant lexicon" in two, one for Sentiment and one for Fun. This should help make the score assignment more straigthforward. Make sure to transfer the lexicon used to assign the fun score to the second column. 
- As for commentaries to help you. I recommend looking at Alan Sommerstein, _Aristophanes: Wasps. Introduction, Translation and Commentary_, plus the text of _Wasps_ published for Penguin by the same editor. If you are on campus you may get both from the library, but if you are not, reply to this comment and I'll send them to you.

**Comment by bailsy6** [comment]
Okay I updated the lexicon and added the criteria to the documentation file. Could you send those texts to me as I am not on campus?
